"""PDF itinerary export with Unicode support via fpdf2."""
from __future__ import annotations

import io
from pathlib import Path
from typing import Any, Dict, List, Optional

from fpdf import FPDF

from waypoint.config import FONTS_DIR


def _find_font() -> Optional[Path]:
    """Prefer bundled DejaVu; fall back to common system Unicode fonts."""
    candidates = [
        FONTS_DIR / "DejaVuSans.ttf",
        FONTS_DIR / "DejaVuSansCondensed.ttf",
        Path("/System/Library/Fonts/Supplemental/Arial Unicode.ttf"),
        Path("/Library/Fonts/Arial Unicode.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
        Path("/usr/share/fonts/TTF/DejaVuSans.ttf"),
    ]
    for p in candidates:
        if p.exists():
            return p
    return None


def _safe_text(text: str) -> str:
    """Drop characters a fallback Helvetica build cannot encode."""
    try:
        text.encode("latin-1")
        return text
    except UnicodeEncodeError:
        return text.encode("latin-1", errors="replace").decode("latin-1")


class ItineraryPDF(FPDF):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._ua_family = "Helvetica"
        self._unicode = False

    def footer(self) -> None:
        self.set_y(-15)
        self.set_x(self.l_margin)
        self.set_font(self._ua_family, size=8)
        self.set_text_color(100, 100, 100)
        self.cell(
            0,
            8,
            "Map data (c) OpenStreetMap contributors  |  Generated by Waypoint",
            align="C",
        )


def build_itinerary_pdf(
    itin: Dict[str, Any],
    allowed_pois: Dict[str, Any],
    *,
    pace: str = "",
    interests: Optional[List[str]] = None,
) -> bytes:
    try:
        return _render_pdf(itin, allowed_pois, pace=pace, interests=interests, force_latin=False)
    except Exception:
        return _render_pdf(itin, allowed_pois, pace=pace, interests=interests, force_latin=True)


def _render_pdf(
    itin: Dict[str, Any],
    allowed_pois: Dict[str, Any],
    *,
    pace: str,
    interests: Optional[List[str]],
    force_latin: bool,
) -> bytes:
    font_path = None if force_latin else _find_font()
    pdf = ItineraryPDF(format="A4")
    pdf.set_margins(15, 15, 15)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    if font_path:
        try:
            pdf.add_font("Waypoint", "", str(font_path))
            pdf._ua_family = "Waypoint"
            pdf._unicode = True
        except Exception:
            pdf._ua_family = "Helvetica"
            pdf._unicode = False
    else:
        pdf._ua_family = "Helvetica"
        pdf._unicode = False
    family = pdf._ua_family

    def write_line(text: str, size: int = 11, color=(30, 30, 30), h: float = 6) -> None:
        pdf.set_x(pdf.l_margin)
        pdf.set_font(family, size=size)
        pdf.set_text_color(*color)
        content = text if pdf._unicode else _safe_text(text)
        pdf.multi_cell(pdf.epw, h, content)

    title = itin.get("title") or "Trip Itinerary"
    city = itin.get("city") or ""

    write_line(title, size=18, color=(11, 110, 79), h=9)
    meta = f"Destination: {city}"
    if pace:
        meta += f"  |  Pace: {pace}"
    if interests:
        meta += f"  |  Interests: {', '.join(interests)}"
    write_line(meta, size=11, h=6)
    pdf.ln(2)

    for day in itin.get("days", []) or []:
        dnum = day.get("day")
        write_line(f"Day {dnum}", size=14, color=(11, 110, 79), h=8)

        for block in ("morning", "afternoon", "evening"):
            items = day.get(block, []) or []
            write_line(block.title(), size=11, color=(40, 40, 40), h=6)
            if not items:
                write_line("  -", size=10, color=(120, 120, 120), h=5)
                continue
            for item in items:
                pid = item.get("poi_id", "")
                poi = allowed_pois.get(pid) or {}
                name = poi.get("name") or pid
                cat = poi.get("category") or ""
                why = (item.get("why") or "").strip()
                line = f"  * {name}"
                if cat:
                    line += f" ({cat})"
                write_line(line, size=10, h=5)
                if why:
                    write_line(f"    {why}", size=9, color=(80, 80, 80), h=5)

        notes = (day.get("notes") or "").strip()
        if notes:
            write_line(f"Notes: {notes}", size=9, color=(70, 70, 70), h=5)

        sources = day.get("sources") or []
        if sources:
            src_line = "Sources: " + ", ".join(
                f"{s.get('source', '')} ({s.get('chunk_id', '')})" for s in sources[:6]
            )
            write_line(src_line, size=8, color=(90, 90, 90), h=4)
        pdf.ln(2)

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()
